id: I39A14969
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T18:44:48+00:00'
last_modified: '2022-06-08T02:30:49.826422+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27024
  title: མྱང་ཆོས་འབྱུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    1DCB:
      image_group_id: I1GS52996
      title: ''
      total_pages: 114
      order: 1
      base_file: 1DCB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
