id: P004640
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:46:00.676921
source_metadata:
  id: bdr:W27024
  title: མྱང་ཆོས་འབྱུང་།
  author: ''
  volumes:
    23d3d6f26329467b89926ec32e22aa85:
      image_group_id: I1GS52996
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
