id: P004640
initial_creation_type: ocr
source_metadata:
  id: bdr:W27024
  title: མྱང་ཆོས་འབྱུང་།
  author: ''
  volumes:
    23d3d6f26329467b89926ec32e22aa85:
      image_group_id: I1GS52996
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
